#!/bin/zsh
# Syncs Claude Code memory into typed folders and pushes to GitHub every 4 hours

set -e

REPO_DIR="$HOME/llm-context"
MEMORY_SRC=$(find "$HOME/.claude/projects" -maxdepth 2 -type d -name "memory" -path "*-Users-*" | head -1)

# --- 1. Route memory files into typed folders ---
# Only overwrite files that exist in local memory — don't delete files from other laptops

if [ -d "$MEMORY_SRC" ]; then
  for file in "$MEMORY_SRC"/*.md; do
    [ -f "$file" ] || continue
    filename=$(basename "$file")
    [ "$filename" = "MEMORY.md" ] && continue

    # Extract type from frontmatter (line matching "type: X")
    type=$(awk '/^---/{p++} p==1 && /^type:/{gsub(/^type:[[:space:]]*/, ""); print; exit}' "$file")

    case "$type" in
      user)      cp "$file" "$REPO_DIR/user/$filename" ;;
      feedback)  cp "$file" "$REPO_DIR/feedback/$filename" ;;
      project)   cp "$file" "$REPO_DIR/projects/$filename" ;;
      reference) cp "$file" "$REPO_DIR/references/$filename" ;;
    esac
  done
fi

# --- 2. Auto-generate CONTEXT.md (full aggregated context for pasting into any LLM) ---
CONTEXT="$REPO_DIR/CONTEXT.md"
cat > "$CONTEXT" << 'HEADER'
# Full LLM Context — Lautaro Rshaid
<!-- Auto-generated by sync.sh — do not edit manually -->

This file aggregates all context needed to work with Lautaro.
Paste it as a system prompt in any LLM to get full context.

---
HEADER

echo "\n## Who I am\n" >> "$CONTEXT"
for f in "$REPO_DIR"/user/*.md; do
  [ -f "$f" ] && sed '/^---$/,/^---$/d' "$f" >> "$CONTEXT" && echo "\n---\n" >> "$CONTEXT"
done

echo "\n## Rules & Feedback\n" >> "$CONTEXT"
for f in "$REPO_DIR"/feedback/*.md; do
  [ -f "$f" ] && sed '/^---$/,/^---$/d' "$f" >> "$CONTEXT" && echo "\n---\n" >> "$CONTEXT"
done

echo "\n## Active Projects\n" >> "$CONTEXT"
for f in "$REPO_DIR"/projects/*.md; do
  [ -f "$f" ] && sed '/^---$/,/^---$/d' "$f" >> "$CONTEXT" && echo "\n---\n" >> "$CONTEXT"
done

echo "\n## Ideas\n" >> "$CONTEXT"
for f in "$REPO_DIR"/ideas/*.md; do
  [ -f "$f" ] && sed '/^---$/,/^---$/d' "$f" >> "$CONTEXT" && echo "\n---\n" >> "$CONTEXT"
done

echo "\n## Rules for LLMs\n" >> "$CONTEXT"
for f in "$REPO_DIR"/rules/*.md; do
  [ -f "$f" ] && sed '/^---$/,/^---$/d' "$f" >> "$CONTEXT" && echo "\n---\n" >> "$CONTEXT"
done

echo "\n## References\n" >> "$CONTEXT"
for f in "$REPO_DIR"/references/*.md; do
  [ -f "$f" ] && sed '/^---$/,/^---$/d' "$f" >> "$CONTEXT" && echo "\n---\n" >> "$CONTEXT"
done

echo "\n## Code Examples\n" >> "$CONTEXT"
for f in "$REPO_DIR"/code-examples/*.md; do
  [ -f "$f" ] && sed '/^---$/,/^---$/d' "$f" >> "$CONTEXT" && echo "\n---\n" >> "$CONTEXT"
done

echo "\n_Last synced: $(date '+%Y-%m-%d %H:%M')_" >> "$CONTEXT"

# --- 3. Commit and push ---
cd "$REPO_DIR"

# Ensure remote uses lrshaid credentials
LRSHAID_TOKEN=$(gh auth token --hostname github.com --user lrshaid 2>/dev/null)
if [ -n "$LRSHAID_TOKEN" ]; then
  git remote set-url origin "https://lrshaid:${LRSHAID_TOKEN}@github.com/lrshaid/llm-context.git"
fi

git add -A
git stash
git pull --rebase origin main
git stash pop 2>/dev/null || true

git add -A

if ! git diff --cached --quiet; then
  git -c user.name="lrshaid" -c user.email="lautarorshaid@outlook.com" \
    commit -m "sync: $(date '+%Y-%m-%d %H:%M')"
  git push origin main
  echo "$(date): pushed changes" >> /tmp/llm-context-sync.log
else
  echo "$(date): no changes" >> /tmp/llm-context-sync.log
fi
